# Defaults here https://github.com/bbatsov/rubocop/blob/v0.37.2/config/default.yml

inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - "bin/bundle"
    - "bin/rails"
    - "bin/rake"
    - "bin/setup"
    - "bin/spring"
    - "bin/update"
    - "bin/webpack"
    - "bin/webpack-dev-server"
    - "bin/yarn"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/LambdaCall:
  Exclude:
    - '**/*.jbuilder'

Layout/DotPosition:
  EnforcedStyle: leading

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/BlockDelimiters:
  Description: Avoid using {...} for multi-line blocks (multiline chaining is always
    ugly). Prefer {...} over do...end for single-line blocks.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#single-line-blocks
  Enabled: false

Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  Enabled: false

Style/MultilineBlockChain:
  Description: 'Avoid multi-line chains of blocks.'
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#single-line-blocks
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/Attr:
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/shared_examples/**/*.rb

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
  SupportedStylesForLeadingUnderscores:
    - disallowed
    - required
    - optional

Style/GuardClause:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - as
    - and

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/PredicateMatcher:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
