default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username:
  password:

development:
  <<: *default
  database: event_manager_development


test: &TEST
  <<: *default
  database: event_manager_test

production:
