default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username:
  password:

development:
  <<: *default
  database: event_manager_development


test: &TEST
  <<: *default
  database: event_manager_test

production:

